### ISSUE TITLE
BetterChairs Causes Server Crash in 1.19.1

### ISSUE THREAD

**Issue by IAmEchino** [Sprax2013/BetterChairs#151]
* **Server Version**:  Paper version git-Paper-86 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 4a4ee79)
* **Plugin Version**:  1.5.2

**Describe the bug**
A clear and concise description of the bug.

My server crashed 1 minute and 18 seconds after someone joined. The error mentions BetterChairs multiple times. It seems to have something to do with armor stands. I do not know what the player did, nor what caused the crash, but I hope that the crash log I provide can be of some use.

**To Reproduce**
1. Start up server
2. Have it on for a while
3. Someone joins
4. ???
5. Server crashes due to an entity exception

**Screenshots, Videos, Logs or Errors**
If possible, try uploading images or large logs as an attachment instead of somewhere else to ensure its availability.

**Sections of startup log re: BetterChairs:**

```
[16:26:27] [Server thread/INFO]: [BetterChairs] Loading BetterChairs v1.5.2

[16:26:46] [Server thread/INFO]: [BetterChairs] Enabling BetterChairs v1.5.2

[16:26:46] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: BetterChairs [1.0.0]
```

**The crash:**

```
[15:44:00] [Server thread/ERROR]: Entity threw exception at world:6500.5,76.3,856.5
java.lang.NoSuchMethodError: 'java.util.List de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.cJ()'
	at de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.k(CustomArmorStand.java:39) ~[BetterChairs-v1.5.2.jar:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1156) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:693) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:673) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-86]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:44:00] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1571) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-86]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.List de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.cJ()'
	at de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.shouldDie(CustomArmorStand.java:74) ~[BetterChairs-v1.5.2.jar:?]
	at de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.a(CustomArmorStand.java:70) ~[BetterChairs-v1.5.2.jar:?]
	at net.minecraft.world.entity.Entity.discard(Entity.java:658) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:905) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:693) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:673) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552) ~[paper-1.19.1.jar:git-Paper-86]
	... 5 more
[15:44:00] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NoSuchMethodError: 'java.util.List de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.cJ()'
	at de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.shouldDie(CustomArmorStand.java:74) ~[BetterChairs-v1.5.2.jar:?]
	at de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.a(CustomArmorStand.java:70) ~[BetterChairs-v1.5.2.jar:?]
	at net.minecraft.world.entity.Entity.discard(Entity.java:658) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:905) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:693) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:673) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-86]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-86]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:44:00] [Server thread/ERROR]: This crash report has been saved to: /home/server/Desktop/Minecraft Server Paper/./crash-reports/crash-2022-07-29_15.44.00-server.txt
```

**Additional context**

**Comment by Jackzerox** [comment]
Hi friends, same problema, with my server, starts correctly, but when a player try to use the plugin action, the server crash..

Thank you for your work.


   Running: Paper version git-Paper-99 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) false
   Plugins: { Graves v4.8 com.ranull.graves.Graves [Ranull], LuckPerms v5.4.30 me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin [Luck], SkinsRestorer v14.2.2-SNAPSHOT net.skinsrestorer.bukkit.SkinsRestorer [knat, AlexProgrammerDE, Th3Tr0LLeR, McLive, DoNotSpamPls], BetterChairs v1.5.2 de.sprax2013.betterchairs.BetterChairsPlugin [SpraxDev, BlackScarx], Geyser-Spigot v2.0.6-SNAPSHOT org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin [GeyserMC], TabList v5.6.3 hu.montlikadani.tablist.TabList [montlikadani], PiggyBack v1.7-SNAPSHOT me.coderky.piggyback.PiggyBack [coderky], ActionHealth v3.5.8 com.zeshanaslam.actionhealth.Main [],}
   Warnings: DEFAULT

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-08-03 19:29:29
Description: Exception ticking world

java.lang.NoSuchMethodError: 'java.util.List de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.cJ()'
	at BetterChairs-v1.5.2.jar//de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.shouldDie(CustomArmorStand.java:74)
	at BetterChairs-v1.5.2.jar//de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.a(CustomArmorStand.java:70)
	at net.minecraft.world.entity.Entity.discard(Entity.java:658)
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:905)
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:693)
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:673)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at BetterChairs-v1.5.2.jar//de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.shouldDie(CustomArmorStand.java:74)
	at BetterChairs-v1.5.2.jar//de.sprax2013.betterchairs.nms.v1_19_R1.CustomArmorStand.a(CustomArmorStand.java:70)
	at net.minecraft.world.entity.Entity.discard(Entity.java:658)
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:905)
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:693)
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:673)

-- Affected level --
Details:
	All players: 1 total; [EntityPlayer['nameplayer'/1729, uuid='Removedbyme', l='ServerLevel[world_nether]', x=46.61, y=107.00, z=-221.08, cpos=[2, -14], tl=1102393, v=true](nameplayer at 46.60751068357827,107.0,-221.07939091645568)]
	Chunk stats: 2831
	Level dimension: minecraft:the_nether
	Level spawn location: World: (0,64,-16), Section: (at 0,0,0 in 0,4,-1; chunk contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 672601524 game time, 98480733 day time
	Level name: world_nether
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 9930 (now: false), thunder time: 33536 (now: false)
	Known server brands: vanilla, Paper
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by deanle8** [comment]
same

**Comment by SpraxDev** [comment]
Will be fixed in the next release - Thanks for the reports!
