### ISSUE TITLE
Plugin does not work 1.21

### ISSUE THREAD

**Issue by VenoPhage** [Sprax2013/BetterChairs#236]
* **Server Version**: 1.21-2246-ad910f8 (MC: 1.21)
* **Plugin Version**: 1.9.0

**Describe the bug**
When attempting to sit, nothing happens and console spits out errors

**To Reproduce**
1. Install plugin
2. Use /sit or right click chair

**Screenshots, Videos, Logs or Errors**
```
[17:13:06] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BetterChairs v1.9.0
java.lang.NoClassDefFoundError: Could not initialize class de.sprax2013.betterchairs.third_party.de.tr7zw.nbtapi.NBTReflectionUtil
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.third_party.de.tr7zw.nbtapi.NBTEntity.getCompound(NBTEntity.java:81) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.third_party.de.tr7zw.nbtapi.NBT.modify(NBT.java:278) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.ChairUtils.applyChairProtections(ChairUtils.java:55) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.nms.v1_21_R1.v1_21_R1.spawnChairEntity(v1_21_R1.java:42) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.ChairManager.create(ChairManager.java:95) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.ChairManager.create(ChairManager.java:78) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.EventListener.lambda$onInteract$3(EventListener.java:227) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.EventListener.onInteract(EventListener.java:239) ~[BetterChairs-v1.9.0.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2246-ad910f8]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1949) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1513) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1484) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1443) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1450) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:81) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.third_party.de.tr7zw.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[BetterChairs-v1.9.0.jar:?]
... 34 more
[17:13:06] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BetterChairs v1.9.0
java.lang.NoClassDefFoundError: Could not initialize class de.sprax2013.betterchairs.third_party.de.tr7zw.nbtapi.NBTReflectionUtil
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.third_party.de.tr7zw.nbtapi.NBTEntity.getCompound(NBTEntity.java:81) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.third_party.de.tr7zw.nbtapi.NBT.modify(NBT.java:278) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.ChairUtils.applyChairProtections(ChairUtils.java:55) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.nms.v1_21_R1.v1_21_R1.spawnChairEntity(v1_21_R1.java:42) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.ChairManager.create(ChairManager.java:95) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.ChairManager.create(ChairManager.java:78) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.EventListener.lambda$onInteract$3(EventListener.java:227) ~[BetterChairs-v1.9.0.jar:?]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.EventListener.onInteract(EventListener.java:239) ~[BetterChairs-v1.9.0.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2246-ad910f8]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1949) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1513) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1484) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1443) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1450) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:81) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[purpur-1.21.jar:1.21-2246-ad910f8]
at BetterChairs-v1.9.0.jar/de.sprax2013.betterchairs.third_party.de.tr7zw.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[BetterChairs-v1.9.0.jar:?]
... 34 more
```

**Comment by KabanFriends** [comment]
Can confirm.

**Comment by SpraxDev** [comment]
It worked when I tested it ,_,
I don't want to republish to all those "stores"/plugin pages again 😮‍💨

**Comment by SpraxDev** [comment]
v1.9.1 just released and I tested it on latest Paper and Spigot ^^
